JokesWebApp/Models/ErrorViewModel.cs
namespace JokesWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JokesWebApp/Models/jokes.cs
namespace JokesWebApp.Models
{
    public class jokes
    {
        public int id  { get; set; }
        public string autor { get; set; }
        public string jokesPergunta  { get; set; }
        public string JokeResposta { get; set; }

        public jokes()
        {
            id = 0;
            jokesPergunta = string.Empty;
            JokeResposta = string.Empty;
            autor = string.Empty;

        }


    }
}

JokesWebApp/Controllers/HomeController.cs
using JokesWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JokesWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JokesWebApp/Controllers/jokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JokesWebApp.Data;
using JokesWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace JokesWebApp.Controllers
{
    public class jokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public jokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: jokes
        public async Task<IActionResult> Index()
        {
              return _context.jokes != null ? 
                          View(await _context.jokes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.jokes'  is null.");
        }

        //GET: ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            // return _context.jokes != null ?
            //  View(await _context.jokes.ToListAsync()) :
            // Problem("Entity set 'ApplicationDbContext.jokes'  is null.");
            return View();
        }

        //POST: ShowFormResultados
        public async Task<IActionResult> GetSearchForm(string SearchFrase)
        {
            return _context.jokes != null ?
                     View("Index",await _context.jokes.Where( j => j.jokesPergunta.Contains(SearchFrase)).ToListAsync()) :
                     Problem("entity set 'applicationdbcontext.jokes'  is null.");

        }

        // GET: jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.jokes
                .FirstOrDefaultAsync(m => m.id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // GET: jokes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,jokesPergunta,JokeResposta,autor")] jokes jokes)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                jokes.autor = userId;
                _context.Add(jokes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.jokes.FindAsync(id);
            if (jokes == null)
            {
                return NotFound();
            }
            return View(jokes);
        }

        // POST: jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,jokesPergunta,JokeResposta")] jokes jokes)
        {
            if (id != jokes.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!jokesExists(jokes.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.jokes
                .FirstOrDefaultAsync(m => m.id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // POST: jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.jokes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.jokes'  is null.");
            }
            var jokes = await _context.jokes.FindAsync(id);
            if (jokes != null)
            {
                _context.jokes.Remove(jokes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool jokesExists(int id)
        {
          return (_context.jokes?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

JokesWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo às Piadas Secas</h1>
    <h5>António Reis</h5> 
    <p>Aprenda Sobre <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <img src="https://imgv2-1-f.scribdassets.com/img/document/578608894/original/1adc9ddf12/1693699272?v=1" alt="Piadas Do Deserto" width="30%" height="30%">
</div>

JokesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JokesWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JokesWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JokesWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="jokes" asp-action="Index">Trolagens</a>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="jokes" asp-action="ShowSearchForm">Procurar</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JokesWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JokesWebApp/Views/jokes/Create.cshtml
@model JokesWebApp.Models.jokes

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="jokesPergunta" class="control-label"></label>
                <input asp-for="jokesPergunta" class="form-control" />
                <span asp-validation-for="jokesPergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeResposta" class="control-label"></label>
                <input asp-for="JokeResposta" class="form-control" />
                <span asp-validation-for="JokeResposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/jokes/Delete.cshtml
@model JokesWebApp.Models.jokes

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jokesPergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokesPergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeResposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeResposta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Remover" class="btn btn-danger" /> |
        <a asp-action="Index">De Volta à Listas</a>
    </form>
</div>

JokesWebApp/Views/jokes/Details.cshtml
@model JokesWebApp.Models.jokes

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jokesPergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jokesPergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeResposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeResposta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">De Volta à Lista</a>
</div>

JokesWebApp/Views/jokes/Edit.cshtml
@model JokesWebApp.Models.jokes

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="jokesPergunta" class="control-label"></label>
                <input asp-for="jokesPergunta" class="form-control" />
                <span asp-validation-for="jokesPergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeResposta" class="control-label"></label>
                <input asp-for="JokeResposta" class="form-control" />
                <span asp-validation-for="JokeResposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">De Volta à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/jokes/Index.cshtml
@model IEnumerable<JokesWebApp.Models.jokes>

@{
    ViewData["Title"] = "Index";
}

<h1>Piadas</h1>

<p>
    <a asp-action="Create">Criar Nova</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.jokesPergunta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.autor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.jokesPergunta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.autor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>

JokesWebApp/Views/jokes/ShowSearchForm.cshtml
@model JokesWebApp.Models.jokes

<h4>Procura uma Piada</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetSearchForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label name="JokesPergunta" class="control-label"></label>
                <input name="SearchFrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Procurar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">De Volta à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}